# Generated by Django 4.0.1 on 2022-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textMsg', models.CharField(max_length=5000)),
                ('image1', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
