# Generated by Django 4.0.1 on 2022-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decryptedText', models.CharField(max_length=10000)),
                ('decryptedImage', models.ImageField(blank=True, upload_to='decrypted_images')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
