# Generated by Django 4.0.1 on 2022-02-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_decryptedmessage_encryptedmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecryptedMessage',
        ),
        migrations.DeleteModel(
            name='EncryptedMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
