# Generated by Django 4.0.1 on 2022-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0004_delete_decryptedmessage_delete_encryptedmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decryptedText', models.CharField(max_length=10000)),
                ('decryptedImage', models.ImageField(blank=True, upload_to='images/decrypted')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryptedImage', models.ImageField(blank=True, upload_to='images/encrypted')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textMsg', models.CharField(max_length=5000)),
                ('image1', models.ImageField(blank=True, upload_to='images/front')),
                ('image2', models.ImageField(blank=True, upload_to='images/info')),
            ],
        ),
    ]
