# Generated by Django 4.0.1 on 2022-03-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_hiddeninfocontainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecryptedMessage',
        ),
        migrations.DeleteModel(
            name='EncryptedMessage',
        ),
        migrations.DeleteModel(
            name='ExtractedInfo',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
